trigger: 
- main


pool:
  vmImage: ubuntu-latest

variables:
  - name: ConnectionName
    value: "Non-Prod Deployment SPN"
  - group: databricks-dev-params


stages:
- stage: Test
  displayName: "Test package"
  jobs:
  - job: Test
    displayName: 'Run tests'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python >=3.10'
      inputs:
        versionSpec: '3.10'

    - task: AzureCLI@2
      displayName: 'Fetch SPN credentials for Azure/Databricks connection'
      inputs:
        azureSubscription: $(ConnectionName)
        scriptType: bash
        addSpnToEnvironment: true
        useGlobalConfig: true
        scriptLocation: inlineScript
        inlineScript: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"

    - script: |
        python -m pip install --upgrade pip
        make dev
      displayName: 'Install dependencies'

    - script: |
        make lint
      displayName: 'Code Quality Checks'

    - script: |
        make test
      displayName: 'Test package'
      env:
        DATABRICKS_CLUSTER_ID: $(databricksCluster)
        DATABRICKS_HOST: $(databricksHost)

    - task: PublishTestResults@2
      displayName: 'Publish unit test results'
      condition: always()
      inputs:
        testResultsFormat: 'JUnit' 
        testResultsFiles: '.junittest*.xml' 
